name: SonarCloud Scan

on: 
    workflow_dispatch: 
    # push:
    # pull_request:

env:
  DEFAULT_MAVEN_OPTS: >-
    -Xmx3g
    -XX:ReservedCodeCacheSize=1g
    -XX:+UseG1GC
    -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN
    -Dhttp.keepAlive=false
    -Dmaven.wagon.http.pool=false
  COMPILE_MAVEN_OPTS: >-
    -Xmx3g
    -Dhttp.keepAlive=false
    -Dmaven.wagon.http.pool=false
  MAVEN_COMPILE_COMMAND: >-
    mvn test-compile
    --show-version
    --no-snapshot-updates
    --no-transfer-progress
    --fail-fast
    -pl -:minifi-c2-integration-tests
    -pl -:minifi-integration-tests
    -pl -:minifi-assembly
    -pl -:nifi-assembly
    -pl -:nifi-kafka-connector-assembly
    -pl -:nifi-kafka-connector-tests
    -pl -:nifi-toolkit-encrypt-config
    -pl -:nifi-toolkit-admin
    -pl -:nifi-toolkit-tls
    -pl -:nifi-toolkit-assembly
    -pl -:nifi-registry-assembly
    -pl -:nifi-registry-toolkit-assembly
    -pl -:nifi-runtime-manifest
    -pl -:nifi-runtime-manifest-test
    -pl -:nifi-stateless-assembly
    -pl -:nifi-stateless-processor-tests
    -pl -:nifi-stateless-system-test-suite
    -pl -:nifi-system-test-suite
    -pl -:nifi-nar-provider-assembly
  MAVEN_VERIFY_COMMAND: >-
    mvn verify
    --show-version
    --no-snapshot-updates
    --no-transfer-progress
    --fail-fast
    -D dir-only
    -D disableXmlReport
  MAVEN_BUILD_PROFILES: >-
    -P include-grpc
    -P skip-nifi-bin-assembly
  MAVEN_PROJECTS: >-
    -pl -minifi/minifi-assembly
    -pl -minifi/minifi-c2/minifi-c2-assembly
    -pl -minifi/minifi-toolkit/minifi-toolkit-assembly
    -pl -nifi-registry/nifi-registry-assembly
    -pl -nifi-registry/nifi-registry-toolkit/nifi-registry-toolkit-assembly
    -pl -nifi-stateless/nifi-stateless-assembly
    -pl -nifi-toolkit/nifi-toolkit-assembly

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  static-analysis:
    timeout-minutes: 30
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Cache Maven Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          # Cache Maven modules using a cache key different from setup-java steps
          key: ${{ runner.os }}-maven-static-analysis-${{ hashFiles('**/pom.xml') }}
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Maven Build
        run: >
          mvn validate
          --no-snapshot-updates
          --no-transfer-progress
          --fail-fast
          -P contrib-check
          -P include-grpc
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=alp-nifi-base -Drat.skip=true

 